# Generated by Django 5.2.6 on 2025-09-21 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Configuração')),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=100, verbose_name='Modelo da IA')),
                ('max_tokens', models.IntegerField(default=500, verbose_name='Máximo de Tokens')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Temperatura')),
                ('include_hashtags', models.BooleanField(default=True, verbose_name='Incluir Hashtags')),
                ('max_hashtags', models.IntegerField(default=5, verbose_name='Máximo de Hashtags')),
                ('include_emojis', models.BooleanField(default=True, verbose_name='Incluir Emojis')),
                ('is_default', models.BooleanField(default=False, verbose_name='Configuração Padrão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de IA',
                'verbose_name_plural': 'Configurações de IA',
            },
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Página')),
                ('page_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Página')),
                ('access_token', models.TextField(verbose_name='Token de Acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página do Facebook',
                'verbose_name_plural': 'Páginas do Facebook',
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Template')),
                ('prompt', models.TextField(verbose_name='Prompt para IA')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Post',
                'verbose_name_plural': 'Templates de Posts',
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('generating', 'Gerando Conteúdo'), ('ready', 'Pronto para Publicar'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('generated_content', models.TextField(blank=True, verbose_name='Conteúdo Gerado')),
                ('generated_image_prompt', models.TextField(blank=True, verbose_name='Prompt da Imagem')),
                ('scheduled_time', models.DateTimeField(verbose_name='Horário Agendado')),
                ('facebook_post_id', models.CharField(blank=True, max_length=100)),
                ('facebook_post_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.facebookpage')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.posttemplate')),
            ],
            options={
                'verbose_name': 'Post Agendado',
                'verbose_name_plural': 'Posts Agendados',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo Publicado')),
                ('facebook_post_id', models.CharField(max_length=100)),
                ('facebook_post_url', models.URLField()),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('metrics_updated_at', models.DateTimeField(blank=True, null=True)),
                ('facebook_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.facebookpage')),
                ('scheduled_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.scheduledpost')),
            ],
            options={
                'verbose_name': 'Post Publicado',
                'verbose_name_plural': 'Posts Publicados',
                'ordering': ['-published_at'],
            },
        ),
    ]
