# Generated by Django 5.2.6 on 2025-09-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='auto_sync',
            field=models.BooleanField(default=True, verbose_name='Sincronização Automática'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='can_manage_ads',
            field=models.BooleanField(default=False, verbose_name='Pode Gerenciar Anúncios'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='can_publish',
            field=models.BooleanField(default=False, verbose_name='Pode Publicar'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='can_read_insights',
            field=models.BooleanField(default=False, verbose_name='Pode Ler Métricas'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='category',
            field=models.CharField(blank=True, max_length=255, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='followers_count',
            field=models.IntegerField(default=0, verbose_name='Seguidores'),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização'),
        ),
    ]
