# Generated by Django 5.2.6 on 2025-09-22 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0002_facebookpage_auto_sync_facebookpage_can_manage_ads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('task_name', models.CharField(max_length=255, verbose_name='Nome da Task')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('default_args', models.TextField(blank=True, help_text='JSON com argumentos padrão', verbose_name='Argumentos Padrão')),
                ('default_kwargs', models.TextField(blank=True, help_text='JSON com parâmetros padrão', verbose_name='Parâmetros Padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Task',
                'verbose_name_plural': 'Templates de Tasks',
            },
        ),
        migrations.CreateModel(
            name='CeleryWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='Hostname')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='Total de Tasks')),
                ('active_tasks', models.IntegerField(default=0, verbose_name='Tasks Ativas')),
                ('processed_tasks', models.IntegerField(default=0, verbose_name='Tasks Processadas')),
                ('last_heartbeat', models.DateTimeField(auto_now=True, verbose_name='Último Heartbeat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Worker do Celery',
                'verbose_name_plural': 'Workers do Celery',
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='ID da Task')),
                ('task_name', models.CharField(max_length=255, verbose_name='Nome da Task')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('STARTED', 'Iniciado'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha'), ('RETRY', 'Tentando Novamente'), ('REVOKED', 'Revogado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('args', models.TextField(blank=True, verbose_name='Argumentos')),
                ('kwargs', models.TextField(blank=True, verbose_name='Parâmetros')),
                ('result', models.TextField(blank=True, verbose_name='Resultado')),
                ('traceback', models.TextField(blank=True, verbose_name='Erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('scheduled_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.scheduledpost', verbose_name='Post Agendado')),
            ],
            options={
                'verbose_name': 'Task do Celery',
                'verbose_name_plural': 'Tasks do Celery',
                'ordering': ['-created_at'],
            },
        ),
    ]
