# Generated by Django 5.0 on 2025-10-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0003_celerytasktemplate_celeryworker_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='content',
            field=models.TextField(blank=True, help_text='Conteúdo direto do post (opcional se usar template)', verbose_name='Conteúdo Manual'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='use_markdown',
            field=models.BooleanField(default=False, help_text='Se marcado, o conteúdo será processado como Markdown', verbose_name='Usar Markdown'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template opcional - deixe vazio para conteúdo manual', null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_integration.posttemplate'),
        ),
    ]
