# Generated by Django 5.2.6 on 2025-10-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0004_scheduledpost_content_scheduledpost_use_markdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytask',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='celerytask',
            name='scheduled_post',
        ),
        migrations.DeleteModel(
            name='CeleryTaskTemplate',
        ),
        migrations.DeleteModel(
            name='CeleryWorker',
        ),
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
