# Generated by Django 5.0 on 2025-10-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0005_remove_celerytask_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
