# Generated by Django 5.0 on 2025-10-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_integration", "0006_aiconfiguration_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="auto_posting_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Postagem Automática Habilitada"
            ),
        ),
        migrations.AddField(
            model_name="publishedpost",
            name="auto_generated",
            field=models.BooleanField(
                default=False, verbose_name="Gerado Automaticamente"
            ),
        ),
        migrations.AddField(
            model_name="publishedpost",
            name="content_tone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Tom do Conteúdo"
            ),
        ),
        migrations.AddField(
            model_name="publishedpost",
            name="content_type",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Tipo de Conteúdo"
            ),
        ),
        migrations.AddField(
            model_name="publishedpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("failed", "Falhou"),
                    ("deleted", "Deletado"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="publishedpost",
            name="facebook_post_url",
            field=models.URLField(blank=True),
        ),
    ]
