# Generated by Django 5.2.6 on 2025-10-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0007_facebookpage_auto_posting_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='published_images/', verbose_name='Imagem Publicada'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='generated_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/', verbose_name='Imagem Gerada'),
        ),
    ]
