# Generated by Django 5.0 on 2025-10-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0009_aiconfiguration_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField(default=0, verbose_name='Seguidores')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('page_impressions', models.IntegerField(default=0, verbose_name='Impressões da Página')),
                ('page_impressions_unique', models.IntegerField(default=0, verbose_name='Impressões Únicas')),
                ('page_engaged_users', models.IntegerField(default=0, verbose_name='Usuários Engajados')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='facebook_integration.facebookpage', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Métrica de Página',
                'verbose_name_plural': 'Métricas de Páginas',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['page', '-collected_at'], name='facebook_in_page_id_873f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Comentários')),
                ('shares_count', models.IntegerField(default=0, verbose_name='Compartilhamentos')),
                ('reach', models.IntegerField(default=0, verbose_name='Alcance')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressões')),
                ('engagement_rate', models.FloatField(default=0.0, verbose_name='Taxa de Engajamento (%)')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='facebook_integration.publishedpost', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Métrica de Post',
                'verbose_name_plural': 'Métricas de Posts',
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['post', '-collected_at'], name='facebook_in_post_id_53582e_idx')],
            },
        ),
    ]
