# Generated by Django 5.0 on 2025-10-10 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0010_pagemetrics_postmetrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetrics',
            name='post_clicks',
            field=models.IntegerField(default=0, verbose_name='Cliques no Post'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='post_clicks_unique',
            field=models.IntegerField(default=0, verbose_name='Cliques Únicos'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='reactions_count',
            field=models.IntegerField(default=0, verbose_name='Total de Reações'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='video_views',
            field=models.IntegerField(default=0, verbose_name='Visualizações de Vídeo'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='video_views_unique',
            field=models.IntegerField(default=0, verbose_name='Visualizações Únicas'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='viral_impressions',
            field=models.IntegerField(default=0, verbose_name='Impressões Virais'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aprovado Em'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_posts', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado Por'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Se marcado, o post precisa ser aprovado antes de publicar', verbose_name='Requer Aprovação'),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('generating', 'Gerando Conteúdo'), ('ready', 'Pronto para Publicar'), ('pending_approval', 'Aguardando Aprovação'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
