# Generated by Django 5.0 on 2025-10-14 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0011_postmetrics_post_clicks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmetrics',
            old_name='viral_impressions',
            new_name='impressions_viral',
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='demographics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Demográficos'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_actions_total',
            field=models.IntegerField(default=0, verbose_name='Ações Totais'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_fan_adds',
            field=models.IntegerField(default=0, verbose_name='Novos Fãs'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_fan_removes',
            field=models.IntegerField(default=0, verbose_name='Fãs Perdidos'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_impressions_organic',
            field=models.IntegerField(default=0, verbose_name='Impressões Orgânicas'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_impressions_paid',
            field=models.IntegerField(default=0, verbose_name='Impressões Pagas'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_impressions_viral',
            field=models.IntegerField(default=0, verbose_name='Impressões Virais'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_negative_feedback',
            field=models.IntegerField(default=0, verbose_name='Feedback Negativo'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_post_engagements',
            field=models.IntegerField(default=0, verbose_name='Engajamentos em Posts'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_video_views',
            field=models.IntegerField(default=0, verbose_name='Visualizações de Vídeos'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_views_total',
            field=models.IntegerField(default=0, verbose_name='Visualizações Totais'),
        ),
        migrations.AddField(
            model_name='pagemetrics',
            name='page_views_unique',
            field=models.IntegerField(default=0, verbose_name='Visualizações Únicas'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='engaged_users',
            field=models.IntegerField(default=0, verbose_name='Usuários Engajados'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='impressions_organic',
            field=models.IntegerField(default=0, verbose_name='Impressões Orgânicas'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='impressions_paid',
            field=models.IntegerField(default=0, verbose_name='Impressões Pagas'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='impressions_unique',
            field=models.IntegerField(default=0, verbose_name='Impressões Únicas'),
        ),
        migrations.AddField(
            model_name='postmetrics',
            name='reactions_by_type',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reações por Tipo'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Lead (Facebook)')),
                ('form_id', models.CharField(max_length=100, verbose_name='ID do Formulário')),
                ('form_name', models.CharField(max_length=255, verbose_name='Nome do Formulário')),
                ('is_organic', models.BooleanField(default=True, verbose_name='Lead Orgânico')),
                ('ad_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Anúncio')),
                ('ad_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Anúncio')),
                ('campaign_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Campanha')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Campanha')),
                ('contact_fields', models.JSONField(default=dict, verbose_name='Campos do Contato')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_time', models.DateTimeField(verbose_name='Data de Criação (Facebook)')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='Coletado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='facebook_integration.facebookpage', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['page', '-created_time'], name='facebook_in_page_id_a48b91_idx'), models.Index(fields=['status'], name='facebook_in_status_c77eb9_idx'), models.Index(fields=['lead_id'], name='facebook_in_lead_id_9c6744_idx')],
            },
        ),
    ]
