# Generated by Django 5.0 on 2025-10-14 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_integration', '0012_rename_viral_impressions_postmetrics_impressions_viral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('privacy', models.CharField(choices=[('OPEN', 'Público'), ('CLOSED', 'Fechado'), ('SECRET', 'Secreto')], default='CLOSED', max_length=20)),
                ('member_count', models.IntegerField(default=0)),
                ('cover_photo', models.URLField(blank=True, null=True)),
                ('permalink_url', models.URLField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_publish', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('accessible_by_pages', models.ManyToManyField(blank=True, related_name='accessible_groups', to='facebook_integration.facebookpage')),
            ],
            options={
                'verbose_name': 'Grupo do Facebook',
                'verbose_name_plural': 'Grupos do Facebook',
                'ordering': ['-member_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('published', 'Publicado'), ('failed', 'Falhou'), ('deleted', 'Deletado')], default='published', max_length=20)),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='facebook_integration.facebookgroup')),
                ('page', models.ForeignKey(blank=True, help_text='Página que publicou (se aplicável)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to='facebook_integration.facebookpage')),
            ],
            options={
                'verbose_name': 'Post de Grupo',
                'verbose_name_plural': 'Posts de Grupos',
                'ordering': ['-published_at'],
            },
        ),
    ]
